replicaCount: 1
image:
  repository: ghcr.io/grainneoc/tldr-app
  pullPolicy: IfNotPresent
  tag: 284a836cd6ef01278865fb5e3f356618f405cf9f
containerPort: 8000
imagePullSecrets:
- name: ghcr-secret
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
  - host: 18.201.115.12.nip.io
    paths:
    - path: /
      pathType: Prefix
  tls: []
httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
  - name: gateway
    sectionName: http
  hostnames:
  - chart-example.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers
resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
